package com.ignilumen.uncannyencounters.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

/** Generated by tools/generate_angler_model.py; edit the generator to change geometry. */
public final class CaveAnglerGeometry {
    private CaveAnglerGeometry() {}
    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        CubeListBuilder body = CubeListBuilder.create();
        body.texOffs(0, 0).addBox(-12.0F, -4.0F, -10.0F, 24.0F, 4.0F, 20.0F);
        body.texOffs(0, 32).addBox(-9.0F, 0.0F, -7.0F, 18.0F, 8.0F, 14.0F);
        body.texOffs(0, 32).addBox(-7.0F, 8.0F, -5.0F, 14.0F, 7.0F, 11.0F);
        body.texOffs(0, 0).addBox(-5.0F, 15.0F, -1.0F, 10.0F, 7.0F, 6.0F);
        body.texOffs(0, 64).addBox(-4.0F, 14.0F, -4.0F, 8.0F, 8.0F, 2.0F);
        body.texOffs(0, 0).addBox(-6.0F, 12.0F, -6.0F, 2.0F, 11.0F, 5.0F);
        body.texOffs(0, 0).addBox(4.0F, 12.0F, -6.0F, 2.0F, 11.0F, 5.0F);
        body.texOffs(0, 0).addBox(-4.0F, 22.0F, -5.0F, 8.0F, 2.0F, 5.0F);
        body.texOffs(0, 0).addBox(-11.0F, -0.25F, -9.0F, 3.0F, 7.0F, 3.0F);
        body.texOffs(0, 0).addBox(-7.0F, -0.25F, -9.0F, 3.0F, 12.0F, 3.0F);
        body.texOffs(0, 0).addBox(-2.0F, -0.25F, -9.0F, 3.0F, 10.0F, 3.0F);
        body.texOffs(0, 0).addBox(3.0F, -0.25F, -9.0F, 3.0F, 14.0F, 3.0F);
        body.texOffs(0, 0).addBox(8.0F, -0.25F, -8.0F, 3.0F, 8.0F, 3.0F);
        body.texOffs(0, 0).addBox(-10.0F, 1.0F, -3.0F, 3.0F, 12.0F, 3.0F);
        body.texOffs(0, 0).addBox(8.0F, 1.0F, -3.0F, 3.0F, 15.0F, 3.0F);
        body.texOffs(0, 0).addBox(-9.25F, -0.25F, 4.25F, 3.0F, 10.0F, 3.0F);
        body.texOffs(0, 0).addBox(6.25F, -0.25F, 5.0F, 3.0F, 12.0F, 3.0F);
        body.texOffs(0, 0).addBox(-4.0F, 4.0F, 6.0F, 3.0F, 13.0F, 3.0F);
        body.texOffs(0, 0).addBox(1.0F, 2.0F, 7.0F, 3.0F, 12.0F, 3.0F);
        body.texOffs(0, 0).addBox(-7.25F, 9.0F, -6.25F, 2.0F, 12.0F, 2.0F);
        body.texOffs(0, 0).addBox(5.25F, 10.0F, -6.25F, 2.0F, 10.0F, 2.0F);
        body.texOffs(0, 0).addBox(-3.0F, 16.0F, 3.0F, 3.0F, 8.0F, 3.0F);
        body.texOffs(0, 0).addBox(1.0F, 16.25F, 3.25F, 2.0F, 6.0F, 2.0F);
        body.texOffs(0, 96).addBox(-3.5F, 14.0F, -6.0F, 1.0F, 3.0F, 2.0F);
        body.texOffs(0, 96).addBox(-3.5F, 20.0F, -6.0F, 1.0F, 2.0F, 2.0F);
        body.texOffs(0, 96).addBox(-0.5F, 14.0F, -6.0F, 1.0F, 2.0F, 2.0F);
        body.texOffs(0, 96).addBox(-0.5F, 20.0F, -6.0F, 1.0F, 2.0F, 2.0F);
        body.texOffs(0, 96).addBox(2.5F, 14.0F, -6.0F, 1.0F, 3.0F, 2.0F);
        body.texOffs(0, 96).addBox(2.5F, 20.0F, -6.0F, 1.0F, 2.0F, 2.0F);
        root.addOrReplaceChild("body", body, PartPose.ZERO);
        CubeListBuilder tongue = CubeListBuilder.create();
        tongue.texOffs(0, 64).addBox(-1.0F, 19.75F, -6.5F, 2.0F, 5.0F, 2.0F);
        tongue.texOffs(0, 96).addBox(-2.0F, 24.0F, -7.0F, 4.0F, 1.0F, 2.0F);
        root.addOrReplaceChild("tongue", tongue, PartPose.ZERO);
        return LayerDefinition.create(mesh, 128, 128);
    }
}
